### ISSUE TITLE
To-Do List before Friday, 2019-02-12

### ISSUE THREAD

**Issue by sabrinatkk** [UBC-MDS/Colourblind8#23]
**To - Do list for Friday:**

Research (please provide links and reference):

- [x] Colour Palette for each function # 10 max
    - Hayley : set_prota()
    - Ian: set_trita()
    - Sabrina: set_deutera()

- [x] How to change objects in matplotlib plots

- [x] How to implement a theme function in Python

**Comment by hfboyce** [comment]
https://matplotlib.org/tutorials/colors/colormap-manipulation.html 

This might be useful if we want to make a colormap. 

My colours expressed as hex and matplotlib accepted name: 

|Number| Hex code |
|----|-----------|
|1.| #7D7C01 |
|2.| #4C5631 | 
|3.| #BDBB64|
|4.| #E8E602|
|5.|#0E1079 |
|6.|#3F59E8|
|7.| #35A9E0|
|8.|#C1C1C7|
|9.|#59709E|

**Comment by sabrinatkk** [comment]
Colour Palette: set_deutera()

|Number| Hex code |
|----|-----------|
|1.| #666E95|
|2.| #FFC13D| 
|3.| #2F86E5|
|4.| #ACA6C3|
|5.|#E8C6BA|
|6.|#867065|
|7.| #483E3C|
|8.|#B0860F|
|9.|#005186|
|10.|#FFD9B0|
